### ISSUE TITLE
Would a ChromaShadeSlider setCurrentValue function be valuable?

### ISSUE THREAD

**Issue by V-FEXrt** [joncardasis/ChromaColorPicker#15]
I have the function below that sets the current value of the ChromaShadeSlider

```swift
// This is inside of ChromaShadeSlider.swift
open func setCurrentValue(value: CGFloat){
    currentValue = value
    handleCenterX = (((currentValue / 2)+0.5) * trackLayer.bounds.width) + (handleWidth/2)

    self.layoutHandleFrame()
}
```
would it be valuable to pull in?

It is currently possible to just directly set the current value with `colorPicker.shadeSlider.currentValue = 1.0;` but that doesn't seem to update the handle correctly

**Comment by joncardasis** [comment]
There are a number of layout issues in the current solution. I have begun a list which I will be addressing in the coming weeks.

I am starting a rewrite of a number of features on this project for better customizability. If you have any suggestions you'd like to see in the evolution of this project, please open a new issue with the `EVOLUTION REQUEST` label.
