### ISSUE TITLE
unable to use supportsShadesOfGray

### ISSUE THREAD

**Issue by ghost320** [joncardasis/ChromaColorPicker#16]
I don't know how to use it

**Comment by joris416** [comment]
Hi, I have the same issue. When I install your color picker through cocoa pods, there does not seem to be any parameter named supportsShadesOfGray in any of the files. When I install it manually by downlading it from here, everything seems fine.

Perhaps the color picker is not updated with CocoaPods yet?

**Comment by joncardasis** [comment]
Seems a bit odd, I agree. I'll look into the most recent pod in the trunk and make sure that it's pointing to the right commit as my next action item on this project
