### ISSUE TITLE
Modifying color wheel to be a single line

### ISSUE THREAD

**Issue by fosini** [joncardasis/ChromaColorPicker#24]
Is there any way to modify the color wheel to single line?
<img width="77" alt="screen shot 2018-02-14 at 10 08 08" src="https://user-images.githubusercontent.com/25727882/36195817-0ba044c8-116f-11e8-9980-02e2bf7ec094.png">

**Comment by joncardasis** [comment]
There is no current way for ChromeColorPicker to do this and it is not the intention of the project to be anything but a circular color picker.
