### ISSUE TITLE
Support full RGB color scope

### ISSUE THREAD

**Issue by RastislavMirek** [joncardasis/ChromaColorPicker#25]
Hi, this is a slider with great UX! However to be adopted by apps that is serious about colors it should be support full color scope. As I understand it, Chroma Picker's UI represents HSL model of a color: The radial slider pick Hue value, the horizontal slider picks Luminosity value but there is no slider for chosing Saturation. 

That is very unfortunate omission. I suggest that to add option (property) that will enable choosing any RGB color from RGB scope: It will add one more horizontal slider for Saturation in place of Hex value label. If the hex value label needs to be kept (I do not think it's necessary) in full scope mode it should be in smaller font above new Saturation slider.

It would be also great to have Alpha value slider but I admit that I would not know where to put it without breaking the design.

**Comment by joncardasis** [comment]
Thanks for the insight and suggestions @RastislavMirek, much appreciated! Apologies for a delayed reply on this. I have heard this request a few times now and agree, this should be included in the project. I am currently revisiting a UI rewrite with a better component style and multiple style support for both the existing HSL model and one which supports a full-color spectrum.

I will be addressing this in my rewrite of the project and styling. Any suggestions from your usage would be valuable either in this ticket or a new one with the `EVOLUTION REQUEST` label.

**Comment by vicwinkler** [comment]
These two comments confuse me. 

HSL is NOT the same as HSV/B.

In the code, there are numerous references to Hue, Saturation and Brightness (HSV/B color scheme), and none to HSL (luminescence).

Please clarify the model in the code and the two comments above.

**Comment by joncardasis** [comment]
@vicwinkler Sorry for the typo, you are correct, it should read "HSB" and not HSL.
