### ISSUE TITLE
Picker subviews not aligned on first layout

### ISSUE THREAD

**Issue by monkeywithacupcake** [joncardasis/ChromaColorPicker#27]
In my app, I draw the picker, but the subviews are not centered on the picker. it is very obvious in iPad. 

![screen shot 2018-06-02 at 05 32 47](https://user-images.githubusercontent.com/7316730/40862140-80381480-6626-11e8-85df-dc526d7e9dc4.png)

I'm setting it up like this:
```
        let minwh = 300.0
        let pickerSize = CGSize(width: minwh*0.8, height: minwh*0.8)
        let pickerOrigin = CGPoint(x: view.bounds.midX - pickerSize.width/2, y: view.bounds.midY - pickerSize.height/2)

        /* Create Color Picker */
        colorPicker = ChromaColorPicker(frame: CGRect(origin: pickerOrigin, size: pickerSize))
        colorPicker.translatesAutoresizingMaskIntoConstraints = false
```
and I think the issue is that the subviews are based on the beginning of the frame rect while the color picker is centered in the stack view. 
However, calling `colorPicker.layout()` after the stackview is created does not help.

**Comment by joncardasis** [comment]
I am putting up some changes today which should address this for all users. Thank you.
