### ISSUE TITLE
Make The Hex Field editable

### ISSUE THREAD

**Issue by miwagner1** [joncardasis/ChromaColorPicker#28]
Allow manual color selection via entering its hex via Hex Field.

**Comment by joncardasis** [comment]
I am actually planning to remove the hex field from inside the circle control and move it elsewhere. 

I am starting a rewrite of a number of features on this project for better customizability. If you have any suggestions you'd like to see in the evolution of this project, please open a new issue with the `EVOLUTION REQUEST` label.
