### ISSUE TITLE
Checkmark instead of plus icon on ChromaAddButton

### ISSUE THREAD

**Issue by ElegyD** [joncardasis/ChromaColorPicker#30]
My current "workaround" is this:
```
colorPicker.addButton.plusIconLayer?.removeFromSuperlayer()
colorPicker.addButton.setImage(#imageLiteral(resourceName: "baseline_check_black_24pt"), for: .normal)
colorPicker.addButton.tintColor = .white
colorPicker.addButton.bringSubview(toFront: colorPicker.addButton.imageView!)
```

But it would be nice if the library had this functionality itself.
Maybe an enum of styles with `.plus` and `.checkmark` which when changed, swaps the currently shown `CASShapeLayer`.

**Comment by joncardasis** [comment]
I agree that workout is a bit hacky. Right now there is no plan to support additional types (ex. checkmark) on the addButton. 

I am starting a rewrite of a number of features on this project for better customizability. If you have any suggestions you'd like to see in the evolution of this project, please open a new issue with the `EVOLUTION REQUEST` label.
