### ISSUE TITLE
3 Swift Compiler Warnings with XCode 10 beta 6

### ISSUE THREAD

**Issue by ghowen** [joncardasis/ChromaColorPicker#31]
Pods/ChromaColorPicker/ChromaColorPicker/ChromaShadeSlider.swift:50:14: 'let' properties are implicitly 'final'; use 'public' instead of 'open'

Pods/ChromaColorPicker/ChromaColorPicker/ChromaShadeSlider.swift:51:14: 'let' properties are implicitly 'final'; use 'public' instead of 'open'

Pods/ChromaColorPicker/ChromaColorPicker/ChromaShadeSlider.swift:28:14: 'let' properties are implicitly 'final'; use 'public' instead of 'open'

**Comment by joncardasis** [comment]
Solution merged
