### ISSUE TITLE
adjustToColor() doesn't play nicely with supportsShadesOfGray

### ISSUE THREAD

**Issue by kforte318** [joncardasis/ChromaColorPicker#34]
Hello,

I'm trying to create a pretty simple color selection view and have had a lot of problems with trying to use adjustToColor() with colors only achievable in grayscale. When adjusted to a grayscale color in full color mode or vice versa, the currentColor of the picker seems to become pretty erratic. It's hard to quantify the exact issue, but I think that the adjustToColor() method needs to somehow take grayscale mode into greater consideration.

Thanks,

Kevin

**Comment by joncardasis** [comment]
Closing this issue due for inactivity. If this issue still persists please re-open the issue :).
