### ISSUE TITLE
Xcode 10.2 compiler failed, I can't build my project :(

### ISSUE THREAD

**Issue by ioviov** [joncardasis/ChromaColorPicker#39]
I have updated Xcode to 10.2 and there is compiler failed : (
Please look at image use link below
https://drive.google.com/open?id=1T8ElVDdJVPvWvPMDyZgsM7h_MAWmknUp

To resolve this, you just need to break your expression into smaller parts.

**Comment by valerianb** [comment]
This PR fixes that issue:
https://github.com/joncardasis/ChromaColorPicker/pull/37

You could use my fork until the PR gets merged

**Comment by Easyhong** [comment]
Pod 1.7.2 version adapts Xcode 10.2.1 ChromaColorPicker, please modify it...

**Comment by ioviov** [comment]
@valerianb Thanks

**Comment by ioviov** [comment]
So, now it's working, thanks
You could close this issue

**Comment by zsjenei** [comment]
No, please don't close the issue until the PR is merged.
@joncardasis  please merge the PR, because now the project is still not building. Thank you!

**Comment by joncardasis** [comment]
@zsjenei Can you describe your issue? Which PR addresses the fix?

**Comment by valerianb** [comment]
#37 which addresses the compile issue with the latest Xcode as well as moving to swift 5

**Comment by zsjenei** [comment]
@joncardasis  could you please merge? :)

**Comment by joncardasis** [comment]
@zsjenei merged.
