### ISSUE TITLE
Problems with AutoLayout

### ISSUE THREAD

**Issue by Laptopmini** [joncardasis/ChromaColorPicker#4]
This library has some pretty major issues with AutoLayout that should be looked into. 

I was unable to get the ColorPicker to render properly until I constrained its width and height to a constant. I would of loved to use an aspect ratio constraint with leading+trailing margins to the superview, but no matter the combinations I used, the ColorPicker would render its subviews all over the screen.

I am not an AutoLayout newbie, so I know my constraints were valid. I can provide more detail if needed.

**Comment by Laptopmini** [comment]
After messing around some more with duplicate constraints (with one having lower priority), I figure out how to get the ColorPicker to layout all its subviews properly.

However, for the color picker to render properly during a screen rotation I had to override `didRotateFromInterfaceOrientation` and call `.layout()` within it.

**Comment by joncardasis** [comment]
Apologies getting back so late to these issues. I had some problems with iOS calling some of its native layouts too often or multiple times. Since `.layout()` will redraw everything it can take some time and I'll look into a better way for the project to handle this without needing to override things. I'll also look at `didRotateFromInterfaceOrientation` - good point.

**Comment by ystsoi** [comment]
I add the following method to ChromaColorPicker to solve the issue:

    open override func layoutSubviews() {
        super.layoutSubviews()
        layout()
    }

**Comment by ivanlares** [comment]
Has this issue been solved ? 
When I constraint the color picker, the interface doesn't seem to be drawn at all. 

If I hardcode a frame value for the picker, the picker layout looks good.
I also tried calling `layout()`.


**I set the background color to red**

![simulator screen shot - iphone 5s - 2018-08-18 at 13 58 01](https://user-images.githubusercontent.com/11603927/44303184-ca9cf400-a2ee-11e8-9d36-7684d86846fb.png)

**Comment by wdcurry** [comment]
It is still a tad messy. I have a 1:1 ration and see the center circle and slider to be offset. So close to being an amazing repo.  I have augmented the protocol to give me more data as well.

**Comment by wdcurry** [comment]
Currently adjustToColor loses any inbound alpha. This is not a desirable situation.

**Comment by joncardasis** [comment]
@wdcurry I agree and this is planned to be addressed the rewrite of this component to hold this alpha value.
