### ISSUE TITLE
color picker handle

### ISSUE THREAD

**Issue by Knkush** [joncardasis/ChromaColorPicker#45]
It is impossible to change size of Color Picker Handle, that small circle.

**Comment by joncardasis** [comment]
Currently it is a `handleSize: CGSize` get-only property which is calculated relative to the parent view (ChromaColorPickerView).

**Comment by Knkush** [comment]
yes I know that, but it's very bad(

**Comment by joncardasis** [comment]
The project is currently being rewritten (90% complete) under the `develop` branch. The new UI and design allows for changing the handleSize. Stay tuned for the update, otherwise, feel free to make a PR in the meantime
