### ISSUE TITLE
BUG: adjustToColor does not update the currentColor

### ISSUE THREAD

**Issue by Laptopmini** [joncardasis/ChromaColorPicker#6]
When calling `adjustToColor`, the variable `currentColor` does not always update itself. 

This seems to happen when only the shade of the color was changed. 

Looking at the code, it doesn't make sense since I can see it being set from `adjustToColor`. However, the only fix I've found is to change `currentColor` to a public variable, and to set it to the same value as the one `adjustToColor` is called with:
```
colorPicker.adjustToColor(targetColor)
colorPicker.currentColor = targetColor
```

**Comment by Laptopmini** [comment]
I have forked and fixed `adjustToColor`. Pull Request #7.

**Comment by Laptopmini** [comment]
For those who do not want to wait for the Pull Request, you can change your podfile to the following:
`pod 'ChromaColorPicker', :git => 'https://github.com/Laptopmini/ChromaColorPicker.git', :commit => '3079eb35214f322a5d19fe37e63d8b9a9663fa0f'`

**Comment by joncardasis** [comment]
Fixed.
